sudo: false

language: php

php:
  - 5.6
  - 7.0

before_script:

  - apt-get install imagemagick;
  - echo "autodetect" | pecl install imagick;

install:

  - composer install;


script:

  - phpunit tests;

after_script:
