sudo: required

language: php

php:
  - 7.0
  - 7.1

before_script:
  - sudo apt-get install imagemagick;
  - echo "autodetect" | pecl install imagick;
  - echo "extension = imagick.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini


install:
  - composer install;

script:
  - phpunit tests;

after_script:
