FORMAT: 1A
HOST: http://demo.rokfor.ch

# Rokfor Slim
TODO: Add Description

# File Proxy [/api/proxy/contribution:id/base64string]

## File Proxy [GET]
file proxy


# Api Contribution 26 [/api/contribution/26]

## Contribution [POST]
Updating a contribution


# Api Issues 1 [/api/issues/1{?populate,verbose,data}]

## Issues [GET]
Issues Query
+ Parameters
    + populate (, required)

    + verbose (, required)

    + data (, required)



# Api Contribution [/api/contribution]

## Contribution [PUT]
Adding new Contributions

+ Request (application/json)
    + Attributes (ContributionRequest)


# Api Contributions 1 1 [/api/contributions/1/1{?populate}]

## Contributions [GET]
+ Parameters
    + populate (, required)



# Api Books [/api/books]

## Books [GET]
Books Query


# Api Contribution 17 [/api/contribution/17]

## Contribution [GET]


# Api Chapters [/api/chapters{?populate,verbose,data}]

## Chapters [GET]
Chapters Query
+ Parameters
    + populate (, required)

    + verbose (, required)

    + data (, required)



# Api Login [/api/login]

## Login [POST]
Logging into the api for subsequent POST or PUT calls. Login generates a JWT token based on the username and the r/w api key.
+ Parameters
    + username (, required)

    + apikey (, required)



# Data Structures

## ContributionRequest (object)


### Properties
+ `Template` (number, required) 
+ `Name` (string, required) 
+ `Chapter` (number, required) 
+ `Issue` (number, required) 
+ `Status` (string, required)